### ISSUE TITLE
[BUG]docker镜像不能下载，源码编译也不行。

### ISSUE THREAD

**Issue by lukemin** [andatoshiki/toshiki-proxypool#98]
- [Y] I'm using the newest release version, and bug isn't solved
  我使用的是最新的release版本，Bug仍未解决
- [Y] I've tested on the newest master, and bug isn't solved
  我测试的是最新master分支，Bug仍未解决
- [Y] I've searched the issues and there's not a similar one
  我已经查看过其他issue，没有类似的情况

Bug Version出现Bug的版本：v0.x.x  
Environment操作环境：heroku/ubuntu/mac
  
## Description 问题描述
docker pull docker.pkg.github.com/andatoshiki/toshiki-proxypool/proxypool:latest
Error response from daemon: Head "https://docker.pkg.github.com/v2/andatoshiki/toshiki-proxypool/proxypool/manifests/latest": no basic auth credentials

docker login https://docker.pkg.github.com
Username:****
Password: 
WARNING! Your password will be stored unencrypted in /root/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store
Docker pull docker.pkg.github.com/andatoshiki/toshiki-proxypool/proxypool:latest
Error response from daemon: manifest unknown

源码编译：
root@instance-20210810-1659:/home/ubuntu# go get -u -v github.com/andatoshiki/toshiki-proxypool
go: go.mod file not found in current directory or any parent directory.
	'go get' is no longer supported outside a module.
	To build and install a command, use 'go install' with a version,
	like 'go install example.com/cmd@latest'
	For more information, see https://golang.org/doc/go-get-install-deprecation
	or run 'go help get' or 'go help install'.
root@instance-20210810-1659:/home/ubuntu# go version
go version go1.19.1 linux/amd64

**Comment by andatoshiki** [comment]
Hi, lukemin, apologizing first,  thorough documentation writeup on this program currently is WIP in regard to my laziness + heavy procrastination from school, [andatoshiki/toshiki-notebook](github.com/andatoshiki/toshiki-notebook) is the repo I build my documentation site, but I have left it untouched for a long time, since there appears to be people using this forked program, I'll reserve some extra time aside from school works when I am spare for self-hosted deployments. BUT I do not guarantee when it will be finished, I'll have you notified as soon as I am done.

For your question,

1. I'm personally not a fan of docker, since this program is a fork of the [original](https://github.com/zu1k/proxypool) author, as he/him left the project abandoned due to complaints from users. I've followed down the way on how the original developer publish releases, instead of manually building binaries outputs then upload these artifacts from platforms to platforms, I used GitHub action as one of the easier CI tools instead.
    - As I have mentioned above, no thorough documentation are written. I've only switched docker registry from dockerhub to ghcr.io (GitHub's docker image registry). Yet you might feel weird on half of the README of this the project is written in English on the intro section, the other half is in Chinese, here's the explanation. There are some extra step if you prefer docker deployments, ports are required to be released before you proceed.

2. Response to your second issue, still, documentation are still not thourough. If you intend to self build binaries from source, go version below `1.17.x` is required if you had a quick skim through the action config files under `.github` folder, named in `go.yml`, as you posted your logs `go version go1.19.1 linux/amd64` exists, I believe that's definitely the reason what caused failure on binary builds. Referring to this [article](https://go.dev/doc/go-get-install-deprecation), quoted in follow,

> Starting in Go 1.17, installing executables with go get is deprecated. go install may be used instead.
> In Go 1.18, go get will no longer build packages; it will only be used to add, update, or remove dependencies in go.mod. Specifically, go get will always act as if the -d flag were enabled.

The traditional `go-get` command is deprecated starting version `1.18.x` for installing necessary dependencies and packages for projects. By far your **best bet** on self-hosting is to download the binaries built by myself under the release section of this repo before I write up docs (still).

Above are the explanation I would extend to clarify confusions, hope these helps. And if you are interested in writing documentations or contributing please let me know, always welcomed.

And once again, thank you for noticing rebased projects on GitHub from the originals. We are just a small piece of unknowns in clouds waiting for discoveries from new users, yet serves as a booster for us to keep everything updated from procrastination. I'll keep up maintaining this project, no worries :)

**Comment by andatoshiki** [comment]
PR approved, will be closing this regarding successful deploy trial, thanks!
